language: python
python:
  - "3.6"
env:
  - TESTPATH=WebApp
  - TESTPATH=Consumer
  - TESTPATH=PRODUCER
# command to install dependencies
install:
  - pip install -r $TESTPATH/requirements.txt
# command to run tests
script:
  - pytest -q $TESTPATH/test_main.py