runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3
  
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.0
  disk_size_gb: 10

beta_settings:
    cloud_sql_instances: INSTANCE_CONNECTION_NAME

env_variables:
    SQLALCHEMY_DATABASE_URI: mysql+pymysql://USER:PASSWORD@/DATABASE?unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME
