steps:
# Clone
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/polleyg/gcp-tweets-streaming-pipeline.git']
# Deploy to App Engine
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--version=app-flex']
  dir: 'WebApp'